### ISSUE TITLE
Raise more specific exceptions

### ISSUE THREAD

**Issue by bersbersbers** [NVIDIA/tensorflow-determinism#7]
Some of the exceptions thrown should be more specific to enable specific exception handling. For example, if no patch is available, a `NotImplementedError` could be thrown here:

https://github.com/NVIDIA/tensorflow-determinism/blob/25d4b51006c765fbcec845baa50c59bbe8d14c01/tfdeterminism/patch.py#L75-L76

This allows users to prevent linter messages such as
> Catching too general exception Exception

**Comment by duncanriach** [comment]
Thank you for that feedback. I'll probably include changes to address that in the next release.

**Comment by duncanriach** [comment]
@bersbersbers, your request has been fulfilled by [this commit](https://github.com/NVIDIA/tensorflow-determinism/commit/3ac1c5dea190a8cae8f6e4622d55dc2f9e9ed882).

I chose to use `TypeError`, rather than `NotImplementedError`, for both current cases. In the case where a patch is not available for a given version of TensorFlow, that might be either because it doesn't need a patch or because a patch is not available. The patch code cannot know which is which up-front.

**Comment by duncanriach** [comment]
Closing.
